<?php
namespace lib\datamodel\sql;
// Generated automatically by daogen.
// Do NOT edit this file.
// Any changes made to this file will be overwritten the next time it is generated.

class ConfessionsSubmitted {
	public $id;
	public $src_ip;
	public $author;
	public $title;
	public $body;
	public $timestamp;

	public function defaultAllFields() {
		$this->id = null;
		$this->src_ip = null;
		$this->author = null;
		$this->title = null;
		$this->body = null;
		$this->timestamp = null;
	}

	public function loadFromArray($arr) {
		$this->id = isset($arr['id']) ? (int)$arr['id'] : null;
		$this->src_ip = isset($arr['src_ip']) ? (int)$arr['src_ip'] : null;
		$this->author = isset($arr['author']) ? (string)$arr['author'] : null;
		$this->title = isset($arr['title']) ? (string)$arr['title'] : null;
		$this->body = isset($arr['body']) ? (string)$arr['body'] : null;
		$this->timestamp = isset($arr['timestamp']) ? (int)$arr['timestamp'] : null;
		return $this;
	}
	public function getId() {
		return $this->id;
	}

	public function getSrc_ip() {
		return $this->src_ip;
	}

	public function getAuthor() {
		return $this->author;
	}

	public function getTitle() {
		return $this->title;
	}

	public function getBody() {
		return $this->body;
	}

	public function getTimestamp() {
		return $this->timestamp;
	}

	public function setId($id) {
		$this->id= $id;
	}

	public function setSrc_ip($src_ip) {
		$this->src_ip= $src_ip;
	}

	public function setAuthor($author) {
		$this->author= $author;
	}

	public function setTitle($title) {
		$this->title= $title;
	}

	public function setBody($body) {
		$this->body= $body;
	}

	public function setTimestamp($timestamp) {
		$this->timestamp= $timestamp;
	}

}
